apiVersion: apps/v1

kind: Deployment

metadata:
  name: auth-2-depl
  labels:
    app: auth

spec:
  replicas: 3

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: auth
          image: anyungu/mesauth
          ports:
            - containerPort: 5000
      serviceAccountName: auth-srv-acct
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-srv-acct
---
# apiVersion: v1

# kind: Service

# metadata:
#   name: auth-srv

# spec:
#   selector:
#     app: auth

#   ports:
#     - name: auth
#       protocol: TCP
#       port: 5000
#       targetPort: 5000

# apiVersion: v1

# kind: ServiceAccount

# metadata:
#   name: auth
# apiVersion: v1

# kind: ServiceAccount

# metadata:
#   name: auth

# ---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v2
      kind:  Mapping
      name:  auth_srv_mapping
      prefix: /api/v1/
      service: http://auth-srv:80
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 80
      name: auth
      targetPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-srv
#   annotations:
#     getambassador.io/config: |
#       ---
#       apiVersion: ambassador/v1
#       kind:  Mapping
#       name:  auth_srv_mapping
#       prefix: /user/
#       service: auth-sidecar-proxy
# spec:
#   selector:
#     app: auth
#   ports:
#     - port: 80
#       name: auth
#       targetPort: 5000

