apiVersion: apps/v1

kind: Deployment

metadata:
  name: noti
  labels:
    app: noti

spec:
  replicas: 3

  selector:
    matchLabels:
      app: noti

  template:
    metadata:
      labels:
        app: noti
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-protocol": "http"
    spec:
      containers:
        - name: noti
          image: anyungu/mesnoti
          ports:
            - containerPort: 8080
      serviceAccountName: noti
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noti
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: noti-srv
#   # annotations:
#   #   getambassador.io/config: |
#   #     ---
#   #     apiVersion: getambassador.io/v2
#   #     kind:  Mapping
#   #     name:  noti_srv_mapping
#   #     prefix: /api/v1/
#   #     service: http://noti-srv:80

# spec:
#   type: NodePort
#   selector:
#     app: noti
#   ports:
#     - port: 80
#       name: noti
#       targetPort: 8080
