# helm-consul-values.yaml
global:
  datacenter: hashidc1

ui:
  service:
    type: "LoadBalancer"

syncCatalog:
  enabled: true

connectInject:
  enabled: true
  default: true

client:
  enabled: true
  grpc: true

server:
  enabled: true
# IingressGateways:
#   enabled: true
#   gateways:
#     - name: ingress-gateway
#       service:
#         type: LoadBalancer
