name: depl-noti

on:
  push:
    branches:
      - master
    paths:
      - notification-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Maven Package
        run: |
          cd notification-service
          mvn -B clean package -DskipTests

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          path: notification-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anyungu/mesnoti
          tags: latest

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: List clusters
        run: gcloud config set project ${{ secrets.PROJECT_ID }}
      - run: gcloud container clusters list

      - name: Deploy
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.PROJECT_ID }}
          kubectl rollout restart deployment/noti
